# Generated by Django 5.2.3 on 2025-06-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferbely_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks_contracts', to='ferbely_app.task'),
        ),
    ]
