# Generated by Django 5.2.3 on 2025-06-21 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferbely_app', '0002_alter_contract_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_contract', to='ferbely_app.bill'),
        ),
    ]
