# Generated by Django 5.2.3 on 2025-06-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferbely_app', '0003_alter_contract_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
