# Generated by Django 5.2.3 on 2025-08-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferbely_app', '0005_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('repair', 'Repair'), ('cleaning', 'Cleaning'), ('other', 'Other')], default='maintenance', max_length=11),
        ),
    ]
