# Generated by Django 5.2.3 on 2025-08-03 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferbely_app', '0006_alter_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_task', to='ferbely_app.contract'),
        ),
    ]
