# Generated by Django 5.2.3 on 2025-08-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferbely_app', '0007_remove_contract_tasks_task_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
