# Generated by Django 5.2.3 on 2025-08-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferbely_app', '0008_alter_contract_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='user',
            new_name='user_id',
        ),
    ]
