# Generated by Django 5.2.3 on 2025-08-19 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferbely_app', '0009_rename_user_contract_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
    ]
